### ISSUE TITLE
binlog document issues list

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb-binlog#1007]
## Bug Report

Please answer these questions before submitting your issue. Thanks!
1. binlog package don't include in tidb-enterprise-tools-latest-linux-amd64.tar.gz any more.
document: https://docs.pingcap.com/zh/tidb/stable/binlog-control
description in doc: ```对于 v2.1.0 GA 及以上版本，binlogctl 已经包含在 TiDB 的下载包中，其他版本需要单独下载 binlogctl:
       wget https://download.pingcap.org/tidb-enterprise-tools-latest-linux-amd64.tar.gz &&
        wget https://download.pingcap.org/tidb-enterprise-tools-latest-linux-amd64.sha256```

2. relay log don't be deleted Immediately after the binlog finished syncing to target tidb. it deleted when new file created.
document : https://docs.pingcap.com/zh/tidb/stable/tidb-binlog-relay-log
description in doc: ```Drainer 在运行时，如果确认已经将一个 relay log 文件的全部数据都成功同步到下游了，就会马上删除这个文 件，所以 relay log 不会占用过多空间。```

**Comment by csuzhangxc** [comment]
> relay log don't be deleted Immediately after the binlog finished syncing to target tidb. it deleted when new file created.
document : https://docs.pingcap.com/zh/tidb/stable/tidb-binlog-relay-log
description in doc: Drainer 在运行时，如果确认已经将一个 relay log 文件的全部数据都成功同步到下游了，就会马上删除这个文 件，所以 relay log 不会占用过多空间。

refine in https://github.com/pingcap/docs-cn/pull/4867

**Comment by csuzhangxc** [comment]
> binlog package don't include in tidb-enterprise-tools-latest-linux-amd64.tar.gz any more.
document: https://docs.pingcap.com/zh/tidb/stable/binlog-control
description in doc: 对于 v2.1.0 GA 及以上版本，binlogctl 已经包含在 TiDB 的下载包中，其他版本需要单独下载 binlogctl: wget https://download.pingcap.org/tidb-enterprise-tools-latest-linux-amd64.tar.gz && wget https://download.pingcap.org/tidb-enterprise-tools-latest-linux-amd64.sha256

@july2993 PTAL 😢

**Comment by WangXiangUSTC** [comment]
I think we can just remove the description `对于 v2.1.0 GA 及以上版本，binlogctl 已经包含在 TiDB 的下载包中，其他版本需要单独下载 binlogctl: wget https://download.pingcap.org/tidb-enterprise-tools-latest-linux-amd64.tar.gz && wget https://download.pingcap.org/tidb-enterprise-tools-latest-linux-amd64.sha256`, there are very few users using the pre-2.1 GA version now.

**Comment by csuzhangxc** [comment]
> I think we can just remove the description `对于 v2.1.0 GA 及以上版本，binlogctl 已经包含在 TiDB 的下载包中，其他版本需要单独下载 binlogctl: wget https://download.pingcap.org/tidb-enterprise-tools-latest-linux-amd64.tar.gz && wget https://download.pingcap.org/tidb-enterprise-tools-latest-linux-amd64.sha256`, there are very few users using the pre-2.1 GA version now.

removed in https://github.com/pingcap/docs-cn/pull/4960.
