### ISSUE TITLE
pump: lost transaction when ttl exceeded

### ISSUE THREAD

**Issue by you06** [pingcap/tidb-binlog#1024]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

This bug occurs when commit duration is more than 10min.

Use these patches for easy reproducing.

tidb(upstream): https://github.com/you06/tidb/tree/reproduce-slow-commit
binlog(pump): https://github.com/you06/tidb-binlog/tree/reproduce-slow-commit

From upstream, run the following statement

```sql
create table t(id int primary key, val int);
begin;
insert into t values(1, 1);
commit; -- this will block 20 seconds
```

Check downstream.

2. What did you expect to see?

```
MySQL [test]> select * from t;
+----+------+
| id | val  |
+----+------+
|  1 |    1 |
+----+------+
1 row in set (0.044 sec)
```

3. What did you see instead?

```
MySQL [test]> select * from t;
Empty set (0.045 sec)
```

pump's log

```log
[2020/12/08 07:34:04.263 +00:00] [INFO] [storage.go:541] ["known txn is committed from tikv"] ["start ts"=421373629621600257] ["commit ts"=0] [isDDL=false]
```

4. Please provide the relate downstream type and version of drainer.
(run `drainer -V` in terminal to get drainer's version)

```
Release Version: v4.0.8-3-g83984f4
Git Commit Hash: 83984f4a49898f6120157e240ca6a666ddeeafde
Build TS: 2020-11-27 04:55:57
Go Version: go1.15.2
Go OS/Arch: linux/amd64
```

**Comment by csuzhangxc** [comment]
if we add some log in Pump, we can get a non-zero TTL like `26957` and `Action_MinCommitTSPushed`.  @cfzjywxk any advice?

**Comment by csuzhangxc** [comment]
Can this be reproduced in v4.0.8?

**Comment by you06** [comment]
> Can this be reproduced in v4.0.8?

The issue is found in a cluster with latest version of TiDB 4.0. It can be reproduced with  4.0, but the commit time should large than TiDB's ttl duration(default to 600s) and pump's maxTxnTimeoutSecond(600s).

**Comment by csuzhangxc** [comment]
in https://github.com/pingcap/tidb/pull/11999, `GetTxnStatus` changed the API used for TiKV from `CleanupRequest` to `CmdCheckTxnStatus`. all v4.0.x versions should be affected.
