### ISSUE TITLE
drainer panic while tiup cluster patch hotfix v3.0.15-20210820

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/tidb-binlog#1068]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Use tiup cluster patch to install patch for drainer

2. What did you expect to see?
no error happened.

3. What did you see instead?
drainer report panic error.
goroutine 316 [running]:
github.com/pingcap/tidb-binlog/drainer/sync.(*MysqlSyncer).syncMsg(0xc000924b00)
        /home/jenkins/agent/workspace/og_multi_branch_v3.0.15-20210820/go/src/github.com/pingcap/tidb-binlog/drainer/sync/mysql.go:295 +0x282
created by github.com/pingcap/tidb-binlog/drainer/sync.NewMysqlSyncer
        /home/jenkins/agent/workspace/og_multi_branch_v3.0.15-20210820/go/src/github.com/pingcap/tidb-binlog/drainer/sync/mysql.go:191 +0x54d
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x11afbfc]

4. Please provide the relate downstream type and version of drainer.
(run `drainer -V` in terminal to get drainer's version)
Release Version: v3.0.15-20210820
Git Commit Hash: 4dccf052b5708dce9ff3434fa5a76f6c7875f202
Build TS: 2021-08-20 09:30:51
Go Version: go1.13
Go OS/Arch: linux/amd64

**Comment by lichunzhu** [comment]
This problem only exists in a commit that wasn't provided to any user. Close this issue now.
