### ISSUE TITLE
file output of drainer use KindUint64 for KindMysqlBit

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb-binlog#1096]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
get the drainer file output of a table with bit(1) column (see attachment), use reparo to replicate to mysql

[data.drainer.zip](https://github.com/pingcap/tidb-binlog/files/7709012/data.drainer.zip)

2. What did you expect to see?

no error

3. What did you see instead?
the value of column bit(1) becomes null

4. Please provide the relate downstream type and version of drainer.
(run `drainer -V` in terminal to get drainer's version)

**Comment by lance6716** [comment]
I add a test log in https://github.com/pingcap/tidb-binlog/blob/f62ba2ddbc295060cb515d34acc1ebb37881360f/reparo/syncer/util.go#L48-L49

```golang
	case mysql.TypeBit:
		log.Info("lance test", zap.String("value", value.String()))
		value = types.NewDatum(value.GetMysqlBit())
```

the output is 

```
[2021/12/14 13:38:23.415 +08:00] [INFO] [util.go:51] ["lance test"] [value="KindUint64 1"]
[2021/12/14 13:38:23.415 +08:00] [DEBUG] [translate.go:156] ["format value"] ["col name"=is_archive] ["mysql type"=bit] [value=null]
```

**Comment by lance6716** [comment]
@lichunzhu

**Comment by lichunzhu** [comment]
@lance6716 Could you please help use this code to change this part and check whether reparo can work?
https://github.com/pingcap/tidb-binlog/blob/f62ba2d/drainer/translator/mysql.go#L260

**Comment by lance6716** [comment]
```diff
diff --git a/reparo/syncer/util.go b/reparo/syncer/util.go
index e1847514..0d0e8712 100644
--- a/reparo/syncer/util.go
+++ b/reparo/syncer/util.go
@@ -46,7 +46,13 @@ func formatValue(value types.Datum, tp byte) types.Datum {
        case mysql.TypeSet:
                value = types.NewDatum(value.GetMysqlSet().Value)
        case mysql.TypeBit:
-               value = types.NewDatum(value.GetMysqlBit())
+               // Encode bits as integers to avoid pingcap/tidb#10988 (which also affects MySQL itself)
+               val, err := value.GetBinaryLiteral().ToInt(nil)
+               if err != nil {
+                       panic(fmt.Sprintf("%v %v", value.GetBinaryLiteral(), err))
+                       return types.Datum{}
+               }
+               value = types.NewUintDatum(val)
        }
 
        return value
```

the result is not expected (should be one `1` and one `0`)

```
MySQL [oncall]> select * from t;
+---+------------+
| c | is_archive |
+---+------------+
| 1 |            |
| 2 |            |
+---+------------+
2 rows in set (0.001 sec)
```

**Comment by lance6716** [comment]
update

should be one `1` and one `0`

```
MySQL [oncall]> select hex(is_archive) from t;
+-----------------+
| hex(is_archive) |
+-----------------+
| 0               |
| 0               |
+-----------------+
2 rows in set (0.001 sec)
```
