### ISSUE TITLE
pump/drainer: binlog can't replicate data any more if filtered binlog exceeds 2G

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/tidb-binlog#1156]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Use TiDB-Binlog to replicate data from TiDB to kafka. TiDB has some binlogs exceeding 2G, but we have filtered them in drainer.

2. What did you expect to see?
Drainer can replicate data successfully.

3. What did you see instead?
Pump fails and reports `resource limit exceed` error because we set grpc message size to 2G. So as drainer.

4. Please provide the relate downstream type and version of drainer.
(run `drainer -V` in terminal to get drainer's version)

**Comment by VelocityLight** [comment]
update
