### ISSUE TITLE
start drainer server failed with "handle ddl job ID:87, Type:create resource group, State:synced, SchemaState:public"

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb-binlog#1221]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Deploy TiDB cluster and binlog cluster in k8s env

2. What did you expect to see?
drainer should not crash

3. What did you see instead?
drainer crashes with error:
```
[ERROR] [main.go:69] ["start drainer server failed"] [error="handle ddl job ID:87, Type:create resource group, State:synced, SchemaState:public, SchemaID:86, TableID:0, RowCount:0, ArgLen:0, start time: 2023-03-21 04:14:26.009 +0000 UTC
```

4. Please provide the relate downstream type and version of drainer.
(run `drainer -V` in terminal to get drainer's version)

downstream: tidb
drainer:  v7.0.0

**Comment by glorv** [comment]
@bb7133  Do we still support tidb-binlog in v7.x?

**Comment by fubinzh** [comment]
[drainer.log](https://github.com/pingcap/tidb-binlog/files/11025652/drainer.log)

**Comment by nolouch** [comment]
resource group not supports for drainer, I think it's need to ignore like placement rule.
