### ISSUE TITLE
datasource mysql

### ISSUE THREAD

**Issue by liuqian1990** [pingcap/tidb-binlog#588]
Does it support mysql data source?

**Comment by july2993** [comment]
no, if you want to migrate data from mysql to TiDB you can use [DM](https://github.com/pingcap/dm)

**Comment by liuqian1990** [comment]
mysql to mysql or mysql to kafaka?

**Comment by july2993** [comment]
> mysql to mysql or mysql to kafaka?

DM is used only from MySQL/MariaDB to TiDB.
