### ISSUE TITLE
ordering guarantees when the downstream is Kafka

### ISSUE THREAD

**Issue by spjich** [pingcap/tidb-binlog#606]
How's the ordering guarantees when the downstream is Kafka?
With multi partition of Kafka Topic, how will drainer send to different partition?
If only using one partition for ordering guarantees, will the throughput enough to be use?

**Comment by july2993** [comment]
- Ordering guarantees
    * Every change in a transaction is emmited as a message to Kafka as changefeed.
    * In most cases, each Transaction will be emitted once. However, some infrequent conditions (e.g., node failures, network partitions) will cause them to be repeated. This gives our changefeeds an at-least-once delivery guarantee.
    * Once a Transaction has been emitted with some timestamp, no previously unseen transaction will be emitted with a lower timestamp.
- Currently drainer will only write to one partition, partiton 0, we  may support write to multi partition shard by table or PK laster.
- It depends, as some test before, if the size is 5KB, can write 23593 op/second to kafka.

**Comment by suzaku** [comment]
Since the question was answered, I'll close this issue.

**Comment by phamtai97** [comment]
Hi @july2993 
Because I will use consumers to consume data from Kafka, so I need the producer to push data to multiple partitions. 
So I can customize Drainer to push data to multiple partitions instead of 1 partition 0 like an implementation of Tidb-Binlog. 
Does something go wrong when I do?
