### ISSUE TITLE
Chinese garbled，tidb-binlog sync data to Kafka

### ISSUE THREAD

**Issue by bqwzhl20** [pingcap/tidb-binlog#675]
1、tidb 2.1.4，kafka1.1.1

2、db and table character set is utf8mb4

3、chinese garbled as follow：

```
� ¶����̕ ������� �������� ��̋����  22019-07-10 11:41:45 ���� 22019-07-10 11:41:45  22019-07-10 11:41:45 22019-07-10 11:41:45 � ¶����̕ ������� �������� ��̋����  22019-07-10 11:41:45 ���� 22019-07-10 11:41:45  22019-07-10 11:41:45 22019-07-10 11:41:45 
--
```

**Comment by july2993** [comment]
please describe the problem in detail, like give a reproducible process.
is the info you show in `3` using Kafka consumer in console directly?
the Value of Kafka message will be in the format https://github.com/pingcap/tidb-tools/blob/master/tidb-binlog/slave_binlog_proto/proto/binlog.proto, so it can't display directly.
