### ISSUE TITLE
drainer process cannot up when hostname changed

### ISSUE THREAD

**Issue by yester354** [pingcap/tidb-binlog#676]
Hi,i come across a problem when hostname changed .
at first every goes ok,then i shutdown drainer process,at a while,the drainer server hostname was changed by our jobs ,after that i start drainer process,it automately register a new nodeid and  try to  start two drainer process by  using the same port.
accordig to tidb document ,i make  the old node-id state  offline by using tool of binlogctl ,but still not work.some logs as blow

alfter hostname change twice ,there are three drainer service using the same port in the same host
+----------------------------------------------------+-------------------+--------+--------------------+---------------------+
| NodeID                                             | Address           | State  | Max_Commit_Ts      | Update_Time         |
+----------------------------------------------------+-------------------+--------+--------------------+---------------------+
| gdxx-db-xxx060026-db-tidb.xxxxxxxxxxx.com8249:8249 | xxxxxxxx:8249 | online | 409660349216456705 | 2019-07-10 15:17:19 |
| gdxx-db-213060026-db-xxxxxxxxxxx.com:8249     |  xxxxxxxx:8249 | online | 409660349216456705 | 2019-07-10 15:16:46 |
| GDxx-DB-213060026-db-xxxxxxxxxxx.com:8249     |  xxxxxxxx:8249 | paused | 409660349216456705 | 2019-07-10 11:43:36 |
+----------------------------------------------------+-------------------+--------+--------------------+---------------------+

after make it state offline ,it still cannot startup drainer process normal

2019/07/10 15:45:37 main.go:53: [error] start drainer server error, [tikv:9001]PD server timeout[try again later]
github.com/pingcap/errors.AddStack
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174
github.com/pingcap/parser/terror.(*Error).GenWithStackByArgs
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20190118033454-a52e5bde3bd2/terror/terror.go:231
github.com/pingcap/tidb/store/tikv.backoffType.TError
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/backoff.go:146
github.com/pingcap/tidb/store/tikv.(*Backoffer).Backoff
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/backoff.go:248
github.com/pingcap/tidb/store/tikv.(*RegionCache).loadRegion
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/region_cache.go:333
github.com/pingcap/tidb/store/tikv.(*RegionCache).LocateKey
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/region_cache.go:152
github.com/pingcap/tidb/store/tikv.(*Scanner).getData
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/scan.go:151
github.com/pingcap/tidb/store/tikv.(*Scanner).Next
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/scan.go:92
github.com/pingcap/tidb/store/tikv.newScanner
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/scan.go:51
github.com/pingcap/tidb/store/tikv.(*tikvSnapshot).Iter
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/snapshot.go:285
github.com/pingcap/tidb/structure.(*TxStructure).iterateHash
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/structure/hash.go:241
github.com/pingcap/tidb/structure.(*TxStructure).HGetAll
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/structure/hash.go:207
github.com/pingcap/tidb/meta.(*Meta).GetAllHistoryDDLJobs
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/meta/meta.go:663
github.com/pingcap/tidb-binlog/drainer.loadHistoryDDLJobs
        /home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb-binlog/drainer/util.go:83
github.com/pingcap/tidb-binlog/drainer.(*Server).Start
        /home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb-binlog/drainer/server.go:306
main.main
        /home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb-binlog/cmd/drainer/main.go:52
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337

**Comment by yester354** [comment]
How could i  solve this problem,please help me,thanks

**Comment by yester354** [comment]
2019/07/10 15:40:25 version.go:20: [info] Release Version: v2.1.9
2019/07/10 15:40:25 version.go:21: [info] Git Commit Hash: 8c6e097973357cb1de4aa58e8612c5eac60dfed6
2019/07/10 15:40:25 version.go:22: [info] Build TS: 2019-05-09 02:56:41
2019/07/10 15:40:25 version.go:23: [info] Go Version: go1.12
2019/07/10 15:40:25 version.go:24: [info] Go OS/Arch: linuxamd64
2019/07/10 15:40:25 main.go:30: [info] use config: 略
2019/07/10 15:40:25 server.go:102: [info] clusterID of drainer server is 6702230183437009064
2019/07/10 15:40:25 checkpoint.go:49: [info] initialize mysql type checkpoint binlog commitTS = 409660349216456705 with config &{Db:0xc000538440 Schema:tidb_binlog Table:checkpoint ClusterID:6702230183437009064 InitialCommitTS:409660349216456705 CheckPointFile:/apps/dbdat/drainer/savepoint}
2019/07/10 15:40:25 server.go:296: [info] register success, this drainer's node id is gdxx-db-xxx060026-db-tidb.xxxxxxxxxxx.com:8249
2019/07/10 15:40:47 main.go:53: [error] start drainer server error, [tikv:9001]PD server timeout[try again later]
github.com/pingcap/errors.AddStack
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174
github.com/pingcap/parser/terror.(*Error).GenWithStackByArgs
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20190118033454-a52e5bde3bd2/terror/terror.go:231
github.com/pingcap/tidb/store/tikv.backoffType.TError
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/backoff.go:146
github.com/pingcap/tidb/store/tikv.(*Backoffer).Backoff
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/backoff.go:248
github.com/pingcap/tidb/store/tikv.(*RegionCache).loadRegion
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/region_cache.go:333
github.com/pingcap/tidb/store/tikv.(*RegionCache).LocateKey
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/region_cache.go:152
github.com/pingcap/tidb/store/tikv.(*Scanner).getData
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/scan.go:151
github.com/pingcap/tidb/store/tikv.(*Scanner).Next
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/scan.go:92
github.com/pingcap/tidb/store/tikv.newScanner
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/scan.go:51
github.com/pingcap/tidb/store/tikv.(*tikvSnapshot).Iter
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/snapshot.go:285
github.com/pingcap/tidb/structure.(*TxStructure).iterateHash
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/structure/hash.go:241
github.com/pingcap/tidb/structure.(*TxStructure).HGetAll
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/structure/hash.go:207
github.com/pingcap/tidb/meta.(*Meta).GetAllHistoryDDLJobs
        /home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/meta/meta.go:663
github.com/pingcap/tidb-binlog/drainer.loadHistoryDDLJobs
        /home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb-binlog/drainer/util.go:83
github.com/pingcap/tidb-binlog/drainer.(*Server).Start
        /home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb-binlog/drainer/server.go:306
main.main
        /home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb-binlog/cmd/drainer/main.go:52
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337

**Comment by july2993** [comment]
```
2019/07/10 15:45:37 main.go:53: [error] start drainer server error, [tikv:9001]PD server timeout[try again later]
```
is your cluster still working normally, seems it can't connect to PD. is your `pd-urls` config in drainer.toml still the right one?

**Comment by yester354** [comment]
@july2993 
my cluster cannot work normal ，i didnt change any thing of the config，only the drainer server hostname had changed，at last i have to use command of ansible-playbook unsafe_cleanup_data.yml  to clear all the data ,then drainer  work normal,but i lost my data

**Comment by july2993** [comment]
do you mean clean up all data(tikv not only drainer)? the drainer will not affect you tidb cluster, i think you should check what happens to the cluster first.

**Comment by yester354** [comment]
@july2993 
1、my cluster goes every ok
2、i shutdown drainer to test alert
3、before drainer startup，the drainer server hostname was changed
4、i startup drainer process，it automately register another nodeid，and try to start two drainer process with the same port，drainer cannot work normal，this‘s the problem.
5、as drainer work abnormal with duplicate service，i try to offline one of nodeid by using binlogctl tools
6、after offline duplicate nodeid，drainer still work   abnormal
7、i try two stop all the process of tidb（include tikv，tidb，pd and so on)
8、when i startup all the process again，pump and drainer both work abnormal
9、i have change nothing of configs，only startup and stop process , i think the problem maybe inside of pd,so i try to clear all the data of tidb using command of ansible-playbook   unsafe_cleanup_data.yml
10、pump and drainer  work normal

**Comment by july2993** [comment]
drainer will use <hostname>:<port> as NodeID, so if hostname change, it start a new drainer logically, I think we must support to config the node-id later.

**Comment by yester354** [comment]
how could i make drainer work normal after hostname changed，it always try to start two drainer process with same port。

**Comment by july2993** [comment]
- the problems are, if the hostname change, if the drainer restart, it runs using the new node-id as a new drainer instance, and may start syncing to downstream at `initial-commit-ts`, also left the old node-id not running, must mart it offline manual
- currently, there is no way to work around this, we can add the node-id config at next version, so you can set the node-id not using <hostname>:<port>.
