### ISSUE TITLE
What happens when one pump instance crash?

### ISSUE THREAD

**Issue by billhcmus** [pingcap/tidb-binlog#717]
## General Question

Hi,
I'm researching tidb-binlog and confusing about this, for details:

![](https://pingcap.com/images/blog-cn/tidb-ecosystem-tools-1/3.png)

- What happens when Drainer make PullBinlogs(), at the same time Pump instance crash?
- Has any mechanism prevented that threat?

Many thanks.

**Comment by july2993** [comment]
- What happens when Drainer make PullBinlogs(), at the same time Pump instance crash?
  + It will retry and once the pump comes back drainer will work again, note drainer must pull data from all non-offline pump instance for merging the data.
- Has any mechanism prevented that threat?
  + If the crash pump can come back, drainer will work normally again, if not, you can unsafely remove the pump instance(change state to be offline directly using binlogctl) **but will lost part of data in that instance**

**Comment by billhcmus** [comment]
- Thank you for your reply.
- Another question for Drainer, Drainer is a standalone instance so if it crashes, all synchronize process must be stopped until the instance come back, can we implement raft protocol to prevent this problem?

**Comment by july2993** [comment]
do you means implement raft protocol to replicate data in pump?  In theory， we can but there's no plan to do this now.

**Comment by billhcmus** [comment]
yeah, in pump instance we can implement raft protocol, but I mean can we implement raft protocol in Drainer too?

**Comment by july2993** [comment]
There's no data persistence needed by drainer (unless the downstream is backup file saved locally).
If the downstream is MySQL/TiDB, it will be simple to start a new drainer in another node with some more simple solutions.

**Comment by billhcmus** [comment]
thank you, I really appreciate all your help.

**Comment by billhcmus** [comment]
> do you means implement raft protocol to replicate data in pump? In theory， we can but there's no plan to do this now.

Continuing with the mechanism to prevent failure in pump instance,
I think we don't need to implement raft protocol here, but we can use TiKV to storage log instead of the file system and Level DB.
My question is: Can we use TiKV in pump instance?

Thank you.

**Comment by july2993** [comment]
@billhcmus 
yes, we can just save data in TiKV for high reliability instead of saving in the local file system without replication. (but pump don't support this)

**Comment by billhcmus** [comment]
why ping cap team did not choose TiKV for log storage? It effects on performance, right?
