### ISSUE TITLE
Enable drainer to purge old incremental backup data on disk

### ISSUE THREAD

**Issue by shinnosuke-okada** [pingcap/tidb-binlog#724]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, incremental backup data needs to be purged manually if drainer is configured to output files to disk.

**Describe the feature you'd like:**

Implement a retention period feature where drainer automatically purges data that is older than a configured time.
e.g. If 7 days is configured as a retention period, incremental backup data that is older than 7 days is automatically deleted to free up disk space.

**Describe alternatives you've considered:**

N/A

**Teachability, Documentation, Adoption, Migration Strategy:**

For example, a new configuration like the following can be added:
```
# Determines when to remove old data. Effective only if db-type is "file". Defaults to 7d.
retention-time = 30d

**Comment by suzaku** [comment]
Makes sense. If this feature is added with a new option `retention-time`, we'd better set the default value to something like `-1` which means "Don't delete backup files for me", so that we don't surprise users of older versions.
