### ISSUE TITLE
Which version should I use If I want to learn how correctly using `kafka`?

### ISSUE THREAD

**Issue by jingyugao** [pingcap/tidb-binlog#748]

**Comment by july2993** [comment]
do you mean running drainer with db-type = "kafka"?
you can check the docs: https://pingcap.com/docs-cn/v3.0/reference/tools/tidb-binlog/binlog-slave-client/
the output format is in the same format for 2.1 and 3.0.

**Comment by jingyugao** [comment]
> do you mean running drainer with db-type = "kafka"?
> you can check the docs: https://pingcap.com/docs-cn/v3.0/reference/tools/tidb-binlog/binlog-slave-client/
> the output format is in the same format for 2.1 and 3.0.

I want to know how tidb use `kafka` and permit message sequence and never lost even server restart.

**Comment by july2993** [comment]
TiDB(tidb-server) don't use Kafka directly, drainer can gether all binlog and sort by commit timestamp of the transaction and sync to downstream.

you can check out the docs in https://pingcap.com/docs-cn/v3.0/

And maybe some useful article:
https://pingcap.com/blog-cn/tidb-ecosystem-tools-1/
unfinished: https://pingcap.com/blog-cn/#TiDB-Binlog-%E6%BA%90%E7%A0%81%E9%98%85%E8%AF%BB

**Comment by jingyugao** [comment]
> TiDB(tidb-server) don't use Kafka directly, drainer can gether all binlog and sort by commit timestamp of the transaction and sync to downstream.
> 
> you can check out the docs in https://pingcap.com/docs-cn/v3.0/
> 
> And maybe some useful article:
> https://pingcap.com/blog-cn/tidb-ecosystem-tools-1/
> unfinished: https://pingcap.com/blog-cn/#TiDB-Binlog-%E6%BA%90%E7%A0%81%E9%98%85%E8%AF%BB

Sorry，I mean tidb-binlog, I read the document and find it use kafka to sync data from pumb to drainter in some early versions. I want to know how tidb-binlog could permit the message sequence ? So which version code should I read? I find a tag named `kafka`, is this the version use kafka?

**Comment by july2993** [comment]
- The branch `kafka` use Kafka to sync data from pump to drainer, but it' s not supported by the new version TiDB and not suggested to be used now. In this version, drainer will consume the data from Kafka and sort it by commit timestamp. pump just write binlog into Kafka in the order it receives from TiDB.
