### ISSUE TITLE
Calculate the latency between 2 cluster

### ISSUE THREAD

**Issue by billhcmus** [pingcap/tidb-binlog#751]
Hi,

Currently, I want to know the latency between 2 clusters in the sync pipeline. When the Syncer get success after applied the Txn to downstream, can I record the latency between the upstream and downstream by using the `AppliedTS` in `Item` ([code](https://github.com/pingcap/tidb-binlog/blob/master/drainer/sync/syncer.go#L22))

Thank you.

**Comment by july2993** [comment]
`AppliedTS` is only set for sometime (per minute)
When there's no lag, you can check `Reach Duration By Pump`
<img width="812" alt="Screen Shot 2019-09-18 at 2 45 56 PM" src="https://user-images.githubusercontent.com/1681864/65122414-7bf6e780-da23-11e9-8f6b-be17a38bd323.png">
It 's the delay when drainer fetch this txn(binlog) and the physical time of the commit timestamp of the txn,  calculate by   `duration = now() - the physical time of the commit-ts of this txn`

**Comment by billhcmus** [comment]
- Ah, sorry, my question is not clear, I mean use `AppliedTS - Item.Binlog.CommitTS`, but with you answer, I know `AppliedTS is only set for sometime (per minute)` so we can't use AppliedTS.
- Why you don't calculate the duration when the Txn completed instead of `when drainer fetch this txn(binlog)`? I think we can do it [here](https://github.com/pingcap/tidb-binlog/blob/master/drainer/syncer.go#L194) by `now() - item.Binlog.CommitTS`

**Comment by july2993** [comment]
I agree with you to better include the time writing to downstream,  but there's no suck metrics now.

Maybe you can use this [checkpointDelayHistogram](https://github.com/pingcap/tidb-binlog/blob/b8adb11355c590f574396df6708f001027324fe7/drainer/syncer.go#L233
) needs, observe only when saving checkpoint but every txn, it's added by @suzaku before but not display at the dashboard now if deplay by tidb-ansible.

**Comment by billhcmus** [comment]
Thank you.
