### ISSUE TITLE
TiDB Binlog high delay

### ISSUE THREAD

**Issue by billhcmus** [pingcap/tidb-binlog#768]
Hi,
I'm testing TiDB Binlog in real-server but got high delay metrics reported. Detail:

- Binlog Reach Duration By Pump metrics: greater than 1 second

<img width="646" alt="Screen Shot 2019-10-16 at 15 41 47" src="https://user-images.githubusercontent.com/16277024/66903954-8231b100-f02d-11e9-8427-c6c910ab1d1f.png">

- Transaction execution (sql query Time) greater than 1 second

<img width="650" alt="Screen Shot 2019-10-16 at 15 42 39" src="https://user-images.githubusercontent.com/16277024/66904159-d046b480-f02d-11e9-80d8-a53d1f4cc40f.png">

- Then the Checkpoint delay (p99) is 8.7 min and avg is 2.0 min

<img width="654" alt="Screen Shot 2019-10-16 at 15 44 05" src="https://user-images.githubusercontent.com/16277024/66904215-e6ed0b80-f02d-11e9-9e9c-02b8a18dffd5.png">

My Drainer configuration is:

```
....
txn-batch = 1000
worker-count = 48
flag: --cache-binlog-count=6553600
```
- So after 1 second Binlog reach to Drainer, but drainer need > 7s to execute this transaction? Is it right?

Hope your help.

**Comment by july2993** [comment]
seems there's lag at that time near 15:10, may meet high throughput at that time at up stream or run a slow DDL? you can check `Drainer Event` and `ddl` at drainer dashboard for the speed it handled DDL and DML events at that time.


- suggest use a lower txn-batch (<= 100)
- don't config the `cache-binlog-count`, just use the default (with too high value may causes OOM when there's lag), it should be ok to just use the default value after #737  or v3.04

**Comment by billhcmus** [comment]
Thank you so much.
