### ISSUE TITLE
Version 2.1.18, compilation error

### ISSUE THREAD

**Issue by aylen** [pingcap/tidb-binlog#845]
Version ：2.1.18

I am developing based on tidb-binlog, and I get an error during compilation

info：
```
go: finding github.com/pingcap/tidb v2.1.3+incompatible
go: finding github.com/pingcap/tidb v2.1.3+incompatible
# github.com/pingcap/tidb/store/tikv
../../../pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/region_request.go:96:58: unknown field 'StaleEpoch' in struct literal of type errorpb.Error
../../../pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/region_request.go:174:13: e.GetStaleEpoch undefined (type *errorpb.Error has no field or method GetStaleEpoch)
../../../pkg/mod/github.com/pingcap/tidb@v2.1.3+incompatible/store/tikv/region_request.go:214:28: regionErr.GetStaleEpoch undefined (type *errorpb.Error has no field or method GetStaleEpoch)
```
Judging from the error, it is like the error of tidb accessing tikv

**Comment by ericsyh** [comment]
@july2993 PTAL
@aylen is developing some features based on tidb-binlog, the compilation passes on release-3.0 while fail on release-2.1. He need some support on this issue.

**Comment by july2993** [comment]
do you update and deps? seems you update to some un compatible version of deps.

**Comment by aylen** [comment]
I use the official go.mod
```
module aylen/loki

require (
	github.com/BurntSushi/toml v0.3.1
	github.com/Shopify/sarama v1.24.1
	github.com/coreos/bbolt v1.3.3 // indirect
	github.com/coreos/etcd v3.3.18+incompatible // indirect
	github.com/go-sql-driver/mysql v1.4.1
	github.com/gogo/protobuf v1.2.1
	github.com/golang/protobuf v1.3.2
	github.com/google/btree v1.0.0 // indirect
	github.com/google/gofuzz v1.0.0 // indirect
	github.com/google/uuid v1.1.1 // indirect
	github.com/gorilla/mux v1.6.2
	github.com/klauspost/cpuid v1.2.2 // indirect
	github.com/ngaut/log v0.0.0-20160810023011-cec23d3e10b0
	github.com/pingcap/check v0.0.0-20190102082844-67f458068fc8
	github.com/pingcap/errors v0.11.4
	github.com/pingcap/kvproto v0.0.0-20190826051950-fc8799546726 // indirect
	github.com/pingcap/parser v0.0.0-20190718031118-20e37a65d718
	github.com/pingcap/pd v2.1.12+incompatible
	github.com/pingcap/tidb v2.1.3+incompatible
	github.com/pingcap/tidb-binlog v0.0.0-20191030033926-65a1f87f99c0
	github.com/pingcap/tidb-tools v2.1.6+incompatible
	github.com/pingcap/tipb v0.0.0-20190107072121-abbec73437b7
	github.com/prometheus/client_golang v1.0.0
	github.com/siddontang/go v0.0.0-20180604090527-bdc77568d726
	github.com/soheilhy/cmux v0.1.4
	github.com/unrolled/render v0.0.0-20180914162206-b9786414de4d
	github.com/zanmato1984/clickhouse v1.3.4-0.20181106115746-3e9a6b9beb12
	go.etcd.io/bbolt v1.3.3 // indirect
	golang.org/x/net v0.0.0-20190909003024-a7b16738d86b
	golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e // indirect
	golang.org/x/sys v0.0.0-20191029155521-f43be2a4598c // indirect
	google.golang.org/grpc v1.23.1
	sigs.k8s.io/yaml v1.1.0 // indirect
)

go 1.13

```

**Comment by july2993** [comment]
> I use the official go.mod
> 
> ```
> module aylen/loki
> 
> require (
> 	github.com/BurntSushi/toml v0.3.1
> 	github.com/Shopify/sarama v1.24.1
> 	github.com/coreos/bbolt v1.3.3 // indirect
> 	github.com/coreos/etcd v3.3.18+incompatible // indirect
> 	github.com/go-sql-driver/mysql v1.4.1
> 	github.com/gogo/protobuf v1.2.1
> 	github.com/golang/protobuf v1.3.2
> 	github.com/google/btree v1.0.0 // indirect
> 	github.com/google/gofuzz v1.0.0 // indirect
> 	github.com/google/uuid v1.1.1 // indirect
> 	github.com/gorilla/mux v1.6.2
> 	github.com/klauspost/cpuid v1.2.2 // indirect
> 	github.com/ngaut/log v0.0.0-20160810023011-cec23d3e10b0
> 	github.com/pingcap/check v0.0.0-20190102082844-67f458068fc8
> 	github.com/pingcap/errors v0.11.4
> 	github.com/pingcap/kvproto v0.0.0-20190826051950-fc8799546726 // indirect
> 	github.com/pingcap/parser v0.0.0-20190718031118-20e37a65d718
> 	github.com/pingcap/pd v2.1.12+incompatible
> 	github.com/pingcap/tidb v2.1.3+incompatible
> 	github.com/pingcap/tidb-binlog v0.0.0-20191030033926-65a1f87f99c0
> 	github.com/pingcap/tidb-tools v2.1.6+incompatible
> 	github.com/pingcap/tipb v0.0.0-20190107072121-abbec73437b7
> 	github.com/prometheus/client_golang v1.0.0
> 	github.com/siddontang/go v0.0.0-20180604090527-bdc77568d726
> 	github.com/soheilhy/cmux v0.1.4
> 	github.com/unrolled/render v0.0.0-20180914162206-b9786414de4d
> 	github.com/zanmato1984/clickhouse v1.3.4-0.20181106115746-3e9a6b9beb12
> 	go.etcd.io/bbolt v1.3.3 // indirect
> 	golang.org/x/net v0.0.0-20190909003024-a7b16738d86b
> 	golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e // indirect
> 	golang.org/x/sys v0.0.0-20191029155521-f43be2a4598c // indirect
> 	google.golang.org/grpc v1.23.1
> 	sigs.k8s.io/yaml v1.1.0 // indirect
> )
> 
> go 1.13
> ```

this is not the origin go.mod of v2.1.18

**Comment by aylen** [comment]
Because some rack packages are referenced separately, there are some differences compared to the official configuration

**Comment by july2993** [comment]
according to the error info you show the problem is the tidb version is not compatible with the accordin  `github.com/pingcap/kvproto` version you are using. You should use some compatible version.
