### ISSUE TITLE
Drainer should support kafka clientID property

### ISSUE THREAD

**Issue by dixingxing0** [pingcap/tidb-binlog#900]
## Feature Request

**Describe the feature you'd like:**
Our kafka cluster is authenticate by kafka clientID,  since drainer do not support clientID property, we can't push binlog data to kafka cluster.
So drainer should support kafka clientID property in our scenario.

**Comment by WangXiangUSTC** [comment]
We can add a new configuration for Drainer, just like the `kafka-version` https://github.com/pingcap/tidb-binlog/blob/1239134f5437dada58de6f73025ce3fe646dc397/drainer/sync/util.go#L41

**Comment by dijingran** [comment]
Thanks, I am working on this now, if test going well, i will submit a PR.

**Comment by WangXiangUSTC** [comment]
support in https://github.com/pingcap/tidb-binlog/pull/902
