### ISSUE TITLE
drainer flag compatible with the old version

### ISSUE THREAD

**Issue by shuijing198799** [pingcap/tidb-binlog#908]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In the latest binlog  #785 , the startup flags of ~~pump and~~ drainer are incompatible with the old version. For example, disable-detect is changed to enable-detect and disable-dispatch is changed to enable-dispatch.
**Describe the feature you'd like:**

Colleagues can use disable-XXX and enable-XXX. When both exist, disable-XXX takes effect first.
**Describe alternatives you've considered:**

Colleagues can use disable-XXX and enable-XXX. When both exist, disable-XXX takes effect first.
**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by WangXiangUSTC** [comment]
ok, we will take a look @july2993
