### ISSUE TITLE
Kafka drainer as event sourcing

### ISSUE THREAD

**Issue by nhatpdh** [pingcap/tidb-binlog#933]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Drainer currently just use for replication purpose. In some scenario, we want to use drainer as event sourcing for further process.

**Describe the feature you'd like:**
Make new db-type: `kafka-cdc` with some features: 

- One kind of table (table name regex) have one topic: Support customer demand, consumer just consume kind of log they want, not the whole cluster log and filter.
- Simpler message proto: One row change have 1 message, make downstream logic simpler. 
- Add message key: For scalable (not use fixed partition 0), ordering guaranteed (by specify key, or primary key by default. In case pk is not set, use fixed partition)
- Add `checkpoint-topic`: For recovery purpose, we can use a topic with compact clean up policy to store the check point for all drainer.
- Add `DDL-topic`: Store all DDL statement with endless retention, for schema recover in downstream job) 

**Describe alternatives you've considered:**
Just add new config to existing kafka drainer, or new `db-type`?

**Comment by WangXiangUSTC** [comment]
We are planning to replication binlog to other downstream by support, I will inform you when this plugin is supported @pdhnhat
