### ISSUE TITLE
refine the error message if the downstream is kafka and there is a problem with kafka

### ISSUE THREAD

**Issue by GregoryIan** [pingcap/tidb-binlog#940]
## Feature Request

**Is your feature request related to a problem? Please describe:**

from AskTUG post: https://asktug.com/t/topic/33125/4

user can't quickly identify specific errors, and the same is for DBA guys

**Describe the feature you'd like:**

Give more clear clues, such as something wrong with kafka, you need to check kafka

**Comment by july2993** [comment]
has been fixed by https://github.com/pingcap/tidb-binlog/pull/778
